steps:
  # Step 0: Build Collector Image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/project-08246cd8-45a6-45ac-89f/mirpur-repo/mirpur-collector:latest', 
      '-f', 'Dockerfile.collector',
      '.'
    ]

  # Step 1: Build API Image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/project-08246cd8-45a6-45ac-89f/mirpur-repo/mirpur-api:latest', 
      '-f', 'Dockerfile',
      '.'
    ]

  # Step 2: Push Collector Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/project-08246cd8-45a6-45ac-89f/mirpur-repo/mirpur-collector:latest']

  # Step 3: Push API Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/project-08246cd8-45a6-45ac-89f/mirpur-repo/mirpur-api:latest']

  # Step 4: Deploy Collector as a Cloud Run Job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'jobs', 'deploy', 'mirpur-collector-job',
      '--image', 'us-central1-docker.pkg.dev/project-08246cd8-45a6-45ac-89f/mirpur-repo/mirpur-collector:latest',
      '--region', 'us-central1',
      '--memory', '512Mi',
      '--task-timeout', '240s',
      '--max-retries', '1',
      '--set-env-vars=SUPABASE_URL=$_SUPABASE_URL,SUPABASE_KEY=$_SUPABASE_KEY'
    ]

  # Step 5: Deploy API to Cloud Run Service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'mirpur-traffic-api',
      '--image', 'us-central1-docker.pkg.dev/project-08246cd8-45a6-45ac-89f/mirpur-repo/mirpur-api:latest',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--memory', '512Mi',
      '--min-instances', '0',
      '--allow-unauthenticated',
      '--port', '8000',
      '--set-env-vars=SUPABASE_URL=$_SUPABASE_URL,SUPABASE_KEY=$_SUPABASE_KEY'
    ]

images:
  - 'us-central1-docker.pkg.dev/project-08246cd8-45a6-45ac-89f/mirpur-repo/mirpur-collector:latest'
  - 'us-central1-docker.pkg.dev/project-08246cd8-45a6-45ac-89f/mirpur-repo/mirpur-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY
