name: Data Collector Automation

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # আপডেট ভার্সন ব্যবহার করা ভালো

      - name: Setup Python
        uses: actions/setup-python@v5 # আপডেট ভার্সন
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: pip install -r mirpur_data_collector/requirements.txt

      - name: Run Python Script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }} # যদি কোডে os.getenv ব্যবহার করে থাকো
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TOMTOM_API_KEY: ${{ secrets.TOMTOM_API_KEY }}
        run: python mirpur_data_collector/data_pipeline.py