name: Data Collector Automation

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Libraries
        # এখানে ফোল্ডারের নাম যোগ করা হয়েছে
        run: pip install -r mirpur_data_collector/requirements.txt

      - name: Run Python Script
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TOMTOM_API_KEY: ${{ secrets.TOMTOM_API_KEY }}
        # এখানেও ফোল্ডারের নাম যোগ করা হয়েছে
        run: python mirpur_data_collector/data_pipeline.py
